import type { User, Task } from './types';

export const mockUsers: User[] = [
  {
    uid: 'user-01',
    email: 'rizki.putra@sekolah.id',
    name: 'Rizki Firmanto Putra',
    photoURL: 'https://picsum.photos/seed/rizki/200/200',
    position: 'Ketua OSIS',
    divisionName: 'Pengurus Inti',
    accessLevel: 10,
  },
  {
    uid: 'user-02',
    email: 'almira.putri@sekolah.id',
    name: 'Almira Berliana Putri',
    photoURL: 'https://picsum.photos/seed/almira/200/200',
    position: 'Wakil Ketua OSIS',
    divisionName: 'Pengurus Inti',
    accessLevel: 9,
  },
  {
    uid: 'user-03',
    email: 'sela.prihatini@sekolah.id',
    name: 'Sela Marisa Prihatini',
    photoURL: 'https://picsum.photos/seed/sela/200/200',
    position: 'Sekretaris 1',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    uid: 'user-04',
    email: 'dini.safitrah@sekolah.id',
    name: 'Dini Safitrah',
    photoURL: 'https://picsum.photos/seed/dini/200/200',
    position: 'Sekretaris 2',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    uid: 'user-05',
    email: 'inesitarahmawati@sekolah.id',
    name: 'Inesitarahmawati',
    photoURL: 'https://picsum.photos/seed/ines/200/200',
    position: 'Bendahara 1',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    uid: 'user-06',
    email: 'tiara.ramadhani@sekolah.id',
    name: 'Tiara Dwi Ramadhani',
    photoURL: 'https://picsum.photos/seed/tiara/200/200',
    position: 'Bendahara 2',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    uid: 'user-07',
    email: 'syafiqotuzzahro@sekolah.id',
    name: 'Syafiqotuzzahro',
    photoURL: 'https://picsum.photos/seed/syafiq/200/200',
    position: 'Ketua Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 7,
  },
  {
    uid: 'user-08',
    email: 'ayyu.mafaiza@sekolah.id',
    name: "Ayyu'Tiyani Mafaiza",
    photoURL: 'https://picsum.photos/seed/ayyu/200/200',
    position: 'Anggota Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 5,
  },
  {
    uid: 'user-09',
    email: 'rizki.akbar@sekolah.id',
    name: 'Rizki Akbar',
    photoURL: 'https://picsum.photos/seed/akbar/200/200',
    position: 'Anggota Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 5,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-01',
    title: 'Review Proposal Kegiatan 17 Agustus',
    description: 'Final check on budget and schedule for Independence Day events.',
    assignedToUID: 'user-01',
    assignedByName: 'System',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    status: 'pending',
    priority: 'urgent',
  },
  {
    id: 'task-02',
    title: 'Siapkan Laporan Keuangan Bulanan',
    description: 'Compile all financial transactions for the month of July.',
    assignedToUID: 'user-05',
    assignedByName: 'Rizki Firmanto Putra',
    divisionId: 'div-finance',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    status: 'in-progress',
    priority: 'high',
  },
  {
    id: 'task-03',
    title: 'Buat Notulensi Rapat Koordinasi',
    description: 'Transcribe and summarize the coordination meeting from yesterday.',
    assignedToUID: 'user-03',
    assignedByName: 'Almira Berliana Putri',
    dueDate: new Date().toISOString(),
    status: 'pending',
    priority: 'medium',
  },
  {
    id: 'task-04',
    title: 'Koordinasi dengan Divisi Dokumentasi',
    description: 'Ensure documentation team is ready for the upcoming seminar.',
    assignedToUID: 'user-02',
    assignedByName: 'Rizki Firmanto Putra',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    status: 'pending',
    priority: 'high',
  },
  {
    id: 'task-05',
    title: 'Organisir Kegiatan Jumat Bersih',
    description: 'Plan and delegate tasks for the weekly clean-up event.',
    assignedToUID: 'user-07',
    assignedByName: 'Rizki Firmanto Putra',
    divisionId: 'div-01',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 4)).toISOString(),
    status: 'in-progress',
    priority: 'medium',
  },
  {
    id: 'task-06',
    title: 'Bantu persiapan materi dakwah',
    description: 'Research topics for the upcoming religious lecture.',
    assignedToUID: 'user-08',
    assignedByName: 'Syafiqotuzzahro',
    divisionId: 'div-01',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    status: 'pending',
    priority: 'low',
  },
  {
    id: 'task-07',
    title: 'Selesaikan desain poster Idul Adha',
    description: 'Finalize the poster design for the Eid al-Adha event announcement.',
    assignedToUID: 'user-01', // Assigned to Ketua for approval
    assignedByName: 'Divisi Humas',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    status: 'overdue',
    priority: 'high',
  },
];
