import type { User } from './types';

// This data is now only used for initial user seeding/role lookup on first login.
// All runtime data will be fetched from Firestore.
export const mockUsers: Omit<User, 'uid' | 'name' | 'photoURL'> & { email: string }[] = [
  // Pengurus Inti
  {
    email: 'rizki.putra@sekolah.id',
    position: 'Ketua OSIS',
    divisionName: 'Pengurus Inti',
    accessLevel: 10,
  },
  {
    email: 'almira.putri@sekolah.id',
    position: 'Wakil Ketua OSIS',
    divisionName: 'Pengurus Inti',
    accessLevel: 9,
  },
  {
    email: 'sela.prihatini@sekolah.id',
    position: 'Sekretaris 1',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    email: 'dini.safitrah@sekolah.id',
    position: 'Sekretaris 2',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    email: 'inesitarahmawati@sekolah.id',
    position: 'Bendahara 1',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    email: 'tiara.ramadhani@sekolah.id',
    position: 'Bendahara 2',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  // Divisi 1: Keimanan & Ketaqwaan
  {
    email: 'syafiqotuzzahro@sekolah.id',
    position: 'Ketua Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 7,
  },
  {
    email: 'ayyu.mafaiza@sekolah.id',
    position: 'Anggota Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 5,
  },
  {
    email: 'rizki.akbar@sekolah.id',
    position: 'Anggota Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 5,
  },
  // Divisi 2: Organisasi & Arganisasi
  {
    email: 'nihayatuz.cahya@sekolah.id',
    position: 'Ketua Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 7,
  },
  {
    email: 'aditya.rehan@sekolah.id',
    position: 'Anggota Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 5,
  },
  {
    email: 'zhaena.aulya@sekolah.id',
    position: 'Anggota Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 5,
  },
  {
    email: 'anton.praseptian@sekolah.id',
    position: 'Anggota Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 5,
  },
  // Divisi 3: Kehidupan Berbangsa & Bernegara
  {
    email: 'aditya.salim@sekolah.id',
    position: 'Ketua Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 7,
  },
  {
    email: 'ramon.beni@sekolah.id',
    position: 'Anggota Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 5,
  },
  {
    email: 'muhammad.agus@sekolah.id',
    position: 'Anggota Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 5,
  },
  {
    email: 'dewi.ambarsari@sekolah.id',
    position: 'Anggota Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 5,
  },
  // Divisi 4: Dokumentasi & Kesenian
  {
    email: 'nabila.anisa@sekolah.id',
    position: 'Ketua Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 7,
  },
  {
    email: 'diana.pertiwi@sekolah.id',
    position: 'Anggota Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 5,
  },
  {
    email: 'umi.munifatul@sekolah.id',
    position: 'Anggota Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 5,
  },
  {
    email: 'raisha.zahwa@sekolah.id',
    position: 'Anggota Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 5,
  },
  // Divisi 5: Olahraga
  {
    email: 'rizki.alfa@sekolah.id',
    position: 'Ketua Divisi Olahraga',
    divisionId: 'div-05',
    divisionName: 'Divisi Olahraga',
    accessLevel: 7,
  },
  {
    email: 'dinda.fatmawati@sekolah.id',
    position: 'Anggota Divisi Olahraga',
    divisionId: 'div-05',
    divisionName: 'Divisi Olahraga',
    accessLevel: 5,
  },
  {
    email: 'nadia.erra@sekolah.id',
    position: 'Anggota Divisi Olahraga',
    divisionId: 'div-05',
    divisionName: 'Divisi Olahraga',
    accessLevel: 5,
  },
  // Divisi 6: Hubungan Masyarakat
  {
    email: 'ratna.eka@sekolah.id',
    position: 'Ketua Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 7,
  },
  {
    email: 'aldhiffa.zhilal@sekolah.id',
    position: 'Anggota Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 5,
  },
  {
    email: 'najwa.tri@sekolah.id',
    position: 'Anggota Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 5,
  },
  {
    email: 'ririn.dwi@sekolah.id',
    position: 'Anggota Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 5,
  },
  // Divisi 7: Teknologi & Komunikasi
  {
    email: 'fajar.nur@sekolah.id',
    position: 'Ketua Divisi Teknologi & Komunikasi',
    divisionId: 'div-07',
    divisionName: 'Divisi Teknologi & Komunikasi',
    accessLevel: 7,
  },
  {
    email: 'nayla.desty@sekolah.id',
    position: 'Anggota Divisi Teknologi & Komunikasi',
    divisionId: 'div-07',
    divisionName: 'Divisi Teknologi & Komunikasi',
    accessLevel: 5,
  },
  {
    email: 'muhammad.khoerul@sekolah.id',
    position: 'Anggota Divisi Teknologi & Komunikasi',
    divisionId: 'div-07',
    divisionName: 'Divisi Teknologi & Komunikasi',
    accessLevel: 5,
  },
  // Divisi 8: Keamanan & Ketertiban
  {
    email: 'zidane.radinal@sekolah.id',
    position: 'Ketua Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 7,
  },
  {
    email: 'achmad.alvin@sekolah.id',
    position: 'Anggota Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 5,
  },
  {
    email: 'naela.zahrotusifa@sekolah.id',
    position: 'Anggota Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 5,
  },
  {
    email: 'siti.nur.azizah@sekolah.id',
    position: 'Anggota Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 5,
  },
  // Divisi 9: Kesehatan
  {
    email: 'fidi.hartanto@sekolah.id',
    position: 'Ketua Divisi Kesehatan',
    divisionId: 'div-09',
    divisionName: 'Divisi Kesehatan',
    accessLevel: 7,
  },
  {
    email: 'erna.ryaningsih@sekolah.id',
    position: 'Anggota Divisi Kesehatan',
    divisionId: 'div-09',
    divisionName: 'Divisi Kesehatan',
    accessLevel: 5,
  },
  {
    email: 'najwa.tsulistia@sekolah.id',
    position: 'Anggota Divisi Kesehatan',
    divisionId: 'div-09',
    divisionName: 'Divisi Kesehatan',
    accessLevel: 5,
  },
];
