import type { User, Task } from './types';

export const mockUsers: User[] = [
  // Pengurus Inti
  {
    uid: 'user-01',
    email: 'rizki.putra@sekolah.id',
    name: 'Rizki Firmanto Putra',
    photoURL: 'https://picsum.photos/seed/rizki/200/200',
    position: 'Ketua OSIS',
    divisionName: 'Pengurus Inti',
    accessLevel: 10,
  },
  {
    uid: 'user-02',
    email: 'almira.putri@sekolah.id',
    name: 'Almira Berliana Putri',
    photoURL: 'https://picsum.photos/seed/almira/200/200',
    position: 'Wakil Ketua OSIS',
    divisionName: 'Pengurus Inti',
    accessLevel: 9,
  },
  {
    uid: 'user-03',
    email: 'sela.prihatini@sekolah.id',
    name: 'Sela Marisa Prihatini',
    photoURL: 'https://picsum.photos/seed/sela/200/200',
    position: 'Sekretaris 1',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    uid: 'user-04',
    email: 'dini.safitrah@sekolah.id',
    name: 'Dini Safitrah',
    photoURL: 'https://picsum.photos/seed/dini/200/200',
    position: 'Sekretaris 2',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    uid: 'user-05',
    email: 'inesitarahmawati@sekolah.id',
    name: 'Inesitarahmawati',
    photoURL: 'https://picsum.photos/seed/ines/200/200',
    position: 'Bendahara 1',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  {
    uid: 'user-06',
    email: 'tiara.ramadhani@sekolah.id',
    name: 'Tiara Dwi Ramadhani',
    photoURL: 'https://picsum.photos/seed/tiara/200/200',
    position: 'Bendahara 2',
    divisionName: 'Pengurus Inti',
    accessLevel: 8,
  },
  // Divisi 1: Keimanan & Ketaqwaan
  {
    uid: 'user-07',
    email: 'syafiqotuzzahro@sekolah.id',
    name: 'Syafiqotuzzahro',
    photoURL: 'https://picsum.photos/seed/syafiq/200/200',
    position: 'Ketua Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 7,
  },
  {
    uid: 'user-08',
    email: 'ayyu.mafaiza@sekolah.id',
    name: "Ayyu'Tiyani Mafaiza",
    photoURL: 'https://picsum.photos/seed/ayyu/200/200',
    position: 'Anggota Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 5,
  },
  {
    uid: 'user-09',
    email: 'rizki.akbar@sekolah.id',
    name: 'Rizki Akbar',
    photoURL: 'https://picsum.photos/seed/akbar/200/200',
    position: 'Anggota Divisi Keimanan & Ketaqwaan',
    divisionId: 'div-01',
    divisionName: 'Divisi Keimanan & Ketaqwaan',
    accessLevel: 5,
  },
  // Divisi 2: Organisasi & Arganisasi
  {
    uid: 'user-10',
    email: 'nihayatuz.cahya@sekolah.id',
    name: 'Nihayatuz Ziin Cahya',
    photoURL: 'https://picsum.photos/seed/nihayatuz/200/200',
    position: 'Ketua Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 7,
  },
  {
    uid: 'user-11',
    email: 'aditya.rehan@sekolah.id',
    name: 'Aditya Rehan Nur Walid',
    photoURL: 'https://picsum.photos/seed/aditya-rehan/200/200',
    position: 'Anggota Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 5,
  },
  {
    uid: 'user-12',
    email: 'zhaena.aulya@sekolah.id',
    name: 'Zhaena Aulya Putri',
    photoURL: 'https://picsum.photos/seed/zhaena/200/200',
    position: 'Anggota Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 5,
  },
  {
    uid: 'user-13',
    email: 'anton.praseptian@sekolah.id',
    name: 'Anton Praseptian',
    photoURL: 'https://picsum.photos/seed/anton/200/200',
    position: 'Anggota Divisi Organisasi & Arganisasi',
    divisionId: 'div-02',
    divisionName: 'Divisi Organisasi & Arganisasi',
    accessLevel: 5,
  },
  // Divisi 3: Kehidupan Berbangsa & Bernegara
  {
    uid: 'user-14',
    email: 'aditya.salim@sekolah.id',
    name: 'Aditya Nur Salim',
    photoURL: 'https://picsum.photos/seed/aditya-salim/200/200',
    position: 'Ketua Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 7,
  },
  {
    uid: 'user-15',
    email: 'ramon.beni@sekolah.id',
    name: 'Ramon Beni Andani',
    photoURL: 'https://picsum.photos/seed/ramon/200/200',
    position: 'Anggota Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 5,
  },
  {
    uid: 'user-16',
    email: 'muhammad.agus@sekolah.id',
    name: 'Muhammad Agus Ramdhan',
    photoURL: 'https://picsum.photos/seed/agus/200/200',
    position: 'Anggota Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 5,
  },
  {
    uid: 'user-17',
    email: 'dewi.ambarsari@sekolah.id',
    name: 'Dewi Ambarsari',
    photoURL: 'https://picsum.photos/seed/dewi/200/200',
    position: 'Anggota Divisi Kehidupan Berbangsa & Bernegara',
    divisionId: 'div-03',
    divisionName: 'Divisi Kehidupan Berbangsa & Bernegara',
    accessLevel: 5,
  },
  // Divisi 4: Dokumentasi & Kesenian
  {
    uid: 'user-18',
    email: 'nabila.anisa@sekolah.id',
    name: 'Nabila Anisa Putri',
    photoURL: 'https://picsum.photos/seed/nabila/200/200',
    position: 'Ketua Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 7,
  },
  {
    uid: 'user-19',
    email: 'diana.pertiwi@sekolah.id',
    name: 'Diana Pertiwi',
    photoURL: 'https://picsum.photos/seed/diana/200/200',
    position: 'Anggota Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 5,
  },
  {
    uid: 'user-20',
    email: 'umi.munifatul@sekolah.id',
    name: 'Umi Munifatul Khusniati',
    photoURL: 'https://picsum.photos/seed/umi/200/200',
    position: 'Anggota Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 5,
  },
  {
    uid: 'user-21',
    email: 'raisha.zahwa@sekolah.id',
    name: 'Raisha Zahwa',
    photoURL: 'https://picsum.photos/seed/raisha/200/200',
    position: 'Anggota Divisi Dokumentasi & Kesenian',
    divisionId: 'div-04',
    divisionName: 'Divisi Dokumentasi & Kesenian',
    accessLevel: 5,
  },
  // Divisi 5: Olahraga
  {
    uid: 'user-22',
    email: 'rizki.alfa@sekolah.id',
    name: 'Rizki Alfa Ramadhan',
    photoURL: 'https://picsum.photos/seed/rizki-alfa/200/200',
    position: 'Ketua Divisi Olahraga',
    divisionId: 'div-05',
    divisionName: 'Divisi Olahraga',
    accessLevel: 7,
  },
  {
    uid: 'user-23',
    email: 'dinda.fatmawati@sekolah.id',
    name: 'Dinda Fatmawati',
    photoURL: 'https://picsum.photos/seed/dinda/200/200',
    position: 'Anggota Divisi Olahraga',
    divisionId: 'div-05',
    divisionName: 'Divisi Olahraga',
    accessLevel: 5,
  },
  {
    uid: 'user-24',
    email: 'nadia.erra@sekolah.id',
    name: 'Nadia Erra Fadhillah',
    photoURL: 'https://picsum.photos/seed/nadia/200/200',
    position: 'Anggota Divisi Olahraga',
    divisionId: 'div-05',
    divisionName: 'Divisi Olahraga',
    accessLevel: 5,
  },
  // Divisi 6: Hubungan Masyarakat
  {
    uid: 'user-25',
    email: 'ratna.eka@sekolah.id',
    name: 'Ratna Eka Saputri',
    photoURL: 'https://picsum.photos/seed/ratna/200/200',
    position: 'Ketua Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 7,
  },
  {
    uid: 'user-26',
    email: 'aldhiffa.zhilal@sekolah.id',
    name: 'Aldhiffa Zhilal',
    photoURL: 'https://picsum.photos/seed/aldhiffa/200/200',
    position: 'Anggota Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 5,
  },
  {
    uid: 'user-27',
    email: 'najwa.tri@sekolah.id',
    name: 'Najwa Tri Hafsari',
    photoURL: 'https://picsum.photos/seed/najwa-tri/200/200',
    position: 'Anggota Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 5,
  },
  {
    uid: 'user-28',
    email: 'ririn.dwi@sekolah.id',
    name: 'Ririn Dwi Anjani',
    photoURL: 'https://picsum.photos/seed/ririn/200/200',
    position: 'Anggota Divisi Hubungan Masyarakat',
    divisionId: 'div-06',
    divisionName: 'Divisi Hubungan Masyarakat',
    accessLevel: 5,
  },
  // Divisi 7: Teknologi & Komunikasi
  {
    uid: 'user-29',
    email: 'fajar.nur@sekolah.id',
    name: 'Fajar Nur Cahyo',
    photoURL: 'https://picsum.photos/seed/fajar/200/200',
    position: 'Ketua Divisi Teknologi & Komunikasi',
    divisionId: 'div-07',
    divisionName: 'Divisi Teknologi & Komunikasi',
    accessLevel: 7,
  },
  {
    uid: 'user-30',
    email: 'nayla.desty@sekolah.id',
    name: 'Nayla Desty Rahmanita',
    photoURL: 'https://picsum.photos/seed/nayla/200/200',
    position: 'Anggota Divisi Teknologi & Komunikasi',
    divisionId: 'div-07',
    divisionName: 'Divisi Teknologi & Komunikasi',
    accessLevel: 5,
  },
  {
    uid: 'user-31',
    email: 'muhammad.khoerul@sekolah.id',
    name: 'Muhammad Khoerul Azam',
    photoURL: 'https://picsum.photos/seed/khoerul/200/200',
    position: 'Anggota Divisi Teknologi & Komunikasi',
    divisionId: 'div-07',
    divisionName: 'Divisi Teknologi & Komunikasi',
    accessLevel: 5,
  },
  // Divisi 8: Keamanan & Ketertiban
  {
    uid: 'user-32',
    email: 'zidane.radinal@sekolah.id',
    name: 'Zidane Radinal Cusna',
    photoURL: 'https://picsum.photos/seed/zidane/200/200',
    position: 'Ketua Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 7,
  },
  {
    uid: 'user-33',
    email: 'achmad.alvin@sekolah.id',
    name: 'Achmad Alvin',
    photoURL: 'https://picsum.photos/seed/alvin/200/200',
    position: 'Anggota Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 5,
  },
  {
    uid: 'user-34',
    email: 'naela.zahrotusifa@sekolah.id',
    name: 'Naela Zahrotusifa',
    photoURL: 'https://picsum.photos/seed/naela/200/200',
    position: 'Anggota Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 5,
  },
  {
    uid: 'user-35',
    email: 'siti.nur.azizah@sekolah.id',
    name: 'Siti Nur Azizah',
    photoURL: 'https://picsum.photos/seed/siti-azizah/200/200',
    position: 'Anggota Divisi Keamanan & Ketertiban',
    divisionId: 'div-08',
    divisionName: 'Divisi Keamanan & Ketertiban',
    accessLevel: 5,
  },
  // Divisi 9: Kesehatan
  {
    uid: 'user-36',
    email: 'fidi.hartanto@sekolah.id',
    name: 'Fidi Hartanto',
    photoURL: 'https://picsum.photos/seed/fidi/200/200',
    position: 'Ketua Divisi Kesehatan',
    divisionId: 'div-09',
    divisionName: 'Divisi Kesehatan',
    accessLevel: 7,
  },
  {
    uid: 'user-37',
    email: 'erna.ryaningsih@sekolah.id',
    name: 'Erna Ryaningsih',
    photoURL: 'https://picsum.photos/seed/erna/200/200',
    position: 'Anggota Divisi Kesehatan',
    divisionId: 'div-09',
    divisionName: 'Divisi Kesehatan',
    accessLevel: 5,
  },
  {
    uid: 'user-38',
    email: 'najwa.tsulistia@sekolah.id',
    name: 'Najwa Tsulistia Zahra',
    photoURL: 'https://picsum.photos/seed/najwa-zahra/200/200',
    position: 'Anggota Divisi Kesehatan',
    divisionId: 'div-09',
    divisionName: 'Divisi Kesehatan',
    accessLevel: 5,
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-01',
    title: 'Review Proposal Kegiatan 17 Agustus',
    description: 'Final check on budget and schedule for Independence Day events.',
    assignedToUID: 'user-01',
    assignedByName: 'System',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 2)).toISOString(),
    status: 'pending',
    priority: 'urgent',
  },
  {
    id: 'task-02',
    title: 'Siapkan Laporan Keuangan Bulanan',
    description: 'Compile all financial transactions for the month of July.',
    assignedToUID: 'user-05',
    assignedByName: 'Rizki Firmanto Putra',
    divisionId: 'div-finance',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 5)).toISOString(),
    status: 'in-progress',
    priority: 'high',
  },
  {
    id: 'task-03',
    title: 'Buat Notulensi Rapat Koordinasi',
    description: 'Transcribe and summarize the coordination meeting from yesterday.',
    assignedToUID: 'user-03',
    assignedByName: 'Almira Berliana Putri',
    dueDate: new Date().toISOString(),
    status: 'pending',
    priority: 'medium',
  },
  {
    id: 'task-04',
    title: 'Koordinasi dengan Divisi Dokumentasi',
    description: 'Ensure documentation team is ready for the upcoming seminar.',
    assignedToUID: 'user-02',
    assignedByName: 'Rizki Firmanto Putra',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 3)).toISOString(),
    status: 'pending',
    priority: 'high',
  },
  {
    id: 'task-05',
    title: 'Organisir Kegiatan Jumat Bersih',
    description: 'Plan and delegate tasks for the weekly clean-up event.',
    assignedToUID: 'user-07',
    assignedByName: 'Rizki Firmanto Putra',
    divisionId: 'div-01',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 4)).toISOString(),
    status: 'in-progress',
    priority: 'medium',
  },
  {
    id: 'task-06',
    title: 'Bantu persiapan materi dakwah',
    description: 'Research topics for the upcoming religious lecture.',
    assignedToUID: 'user-08',
    assignedByName: 'Syafiqotuzzahro',
    divisionId: 'div-01',
    dueDate: new Date(new Date().setDate(new Date().getDate() + 6)).toISOString(),
    status: 'pending',
    priority: 'low',
  },
  {
    id: 'task-07',
    title: 'Selesaikan desain poster Idul Adha',
    description: 'Finalize the poster design for the Eid al-Adha event announcement.',
    assignedToUID: 'user-01', // Assigned to Ketua for approval
    assignedByName: 'Divisi Humas',
    dueDate: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    status: 'overdue',
    priority: 'high',
  },
];
