// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';

import { useEffect, useState } from 'react';
import { type User as AuthUser, onIdTokenChanged } from 'firebase/auth';
import { doc, onSnapshot } from 'firebase/firestore';

import { useAuth, useFirestore } from '@/firebase';
import type { User } from '@/lib/types';

export function useUser() {
  const auth = useAuth();
  const firestore = useFirestore();
  const [user, setUser] = useState<User | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [authUser, setAuthUser] = useState<AuthUser | null>(null);

  useEffect(() => {
    if (!auth) {
      return;
    }
    const unsubscribe = onIdTokenChanged(auth, (newUser) => {
      setAuthUser(newUser);
    });
    return () => unsubscribe();
  }, [auth]);

  useEffect(() => {
    if (!firestore || !authUser) {
      setUser(null);
      setIsLoading(false);
      return;
    }

    setIsLoading(true);
    const userRef = doc(firestore, 'users', authUser.uid);
    const unsubscribe = onSnapshot(
      userRef,
      (doc) => {
        if (doc.exists()) {
          setUser({ id: doc.id, ...doc.data() } as User);
        } else {
          setUser(null);
        }
        setIsLoading(false);
      },
      (error) => {
        console.error('Error fetching user data:', error);
        setUser(null);
        setIsLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore, authUser]);

  return { user, authUser, isLoading };
}
