// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';
import { useEffect, useState, useRef } from 'react';
import {
  onSnapshot,
  doc,
  type Firestore,
  type DocumentReference,
} from 'firebase/firestore';
import { useFirestore } from '@/firebase';

export function useDoc<T>(pathOrRef: string | DocumentReference | null) {
  const firestore = useFirestore();
  const [data, setData] = useState<T | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const docRef = useRef(pathOrRef);
  docRef.current = pathOrRef;

  useEffect(() => {
    if (!firestore || !docRef.current) {
      setData(null);
      setLoading(false);
      return;
    }

    setLoading(true);

    const ref =
      typeof docRef.current === 'string'
        ? doc(firestore, docRef.current)
        : docRef.current;

    const unsubscribe = onSnapshot(
      ref,
      (snapshot) => {
        if (snapshot.exists()) {
          setData({ id: snapshot.id, ...snapshot.data() } as T);
        } else {
          setData(null);
        }
        setLoading(false);
      },
      (err) => {
        console.error(err);
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore]);

  return { data, loading, error };
}
