// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';
import { useEffect, useState, useRef } from 'react';
import {
  onSnapshot,
  collection,
  query,
  where,
  type Firestore,
  type CollectionReference,
  type Query,
} from 'firebase/firestore';
import { useFirestore } from '@/firebase';

export function useCollection<T>(pathOrQuery: string | Query | null) {
  const firestore = useFirestore();
  const [data, setData] = useState<T[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const queryRef = useRef(pathOrQuery);
  queryRef.current = pathOrQuery;

  useEffect(() => {
    if (!firestore || !queryRef.current) {
      setData(null);
      setLoading(false);
      return;
    }

    setLoading(true);
    
    const ref =
      typeof queryRef.current === 'string'
        ? collection(firestore, queryRef.current)
        : queryRef.current;

    const unsubscribe = onSnapshot(
      ref,
      (snapshot) => {
        const docs = snapshot.docs.map(
          (doc) => ({ id: doc.id, ...doc.data() } as T)
        );
        setData(docs);
        setLoading(false);
      },
      (err) => {
        console.error(err);
        setError(err);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [firestore]);

  return { data, loading, error };
}
