// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';
import React, { useMemo } from 'react';
import { initializeFirebase, FirebaseProvider } from '@/firebase';
import { firebaseConfig } from './config';

export function FirebaseClientProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const firebase = useMemo(() => initializeFirebase(firebaseConfig), []);
  return <FirebaseProvider {...firebase}>{children}</FirebaseProvider>;
}
