// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
import type { FirebaseOptions } from 'firebase/app';

// This is a placeholder for the Firebase config object.
// It will be replaced with your actual Firebase config
// during the build process.
export const firebaseConfig: FirebaseOptions = {
  apiKey: 'REPLACE_WITH_YOUR_API_KEY',
  authDomain: 'REPLACE_WITH_YOUR_AUTH_DOMAIN',
  projectId: 'REPLACE_WITH_YOUR_PROJECT_ID',
  storageBucket: 'REPLACE_WITH_YOUR_STORAGE_BUCKET',
  messagingSenderId: 'REPLACE_WITH_YOUR_MESSAGING_SENDER_ID',
  appId: 'REPLACE_WITH_YOUR_APP_ID',
};
