// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';
import {
  type FirebaseApp,
  type FirebaseOptions,
  initializeApp,
  getApps,
} from 'firebase/app';
import { Auth, getAuth } from 'firebase/auth';
import { Firestore, getFirestore } from 'firebase/firestore';

let app: FirebaseApp;
let auth: Auth;
let firestore: Firestore;

export function initializeFirebase(
  options: FirebaseOptions
): {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
} {
  if (!getApps().length) {
    app = initializeApp(options);
    auth = getAuth(app);
    firestore = getFirestore(app);
  } else {
    app = getApps()[0];
    auth = getAuth(app);
    firestore = getFirestore(app);
  }

  return { app, auth, firestore };
}

export * from './provider';
export * from './auth/use-user';
export * from './firestore/use-collection';
export * from './firestore/use-doc';
