// DO NOT MODIFY. This file is autogenerated by Firebase Studio.
'use client';
import {
  type FirebaseApp,
  type FirebaseOptions,
  initializeApp,
} from 'firebase/app';
import { Auth, getAuth } from 'firebase/auth';
import { Firestore, getFirestore } from 'firebase/firestore';

let app: FirebaseApp | undefined;
let auth: Auth | undefined;
let firestore: Firestore | undefined;

export function initializeFirebase(
  options: FirebaseOptions
): {
  app: FirebaseApp;
  auth: Auth;
  firestore: Firestore;
} {
  if (app) {
    console.warn(
      'Firebase is already initialized. This is probably not what you want.'
    );
  } else {
    app = initializeApp(options);
    auth = getAuth(app);
    firestore = getFirestore(app);
  }

  return { app, auth: auth!, firestore: firestore! };
}

export * from './provider';
export * from './auth/use-user';
export * from './firestore/use-collection';
export * from './firestore/use-doc';
